### ISSUE TITLE
Usage on web: Unexpected token import

### ISSUE THREAD

**Issue by joncursi** [taskrabbit/react-native-parsed-text#40]
Can you use Babel to compile the source code into ES5 before publishing to NPM? I am trying to use this library on a website using `react-native-web`, but browsers can't interpret ES6+

**Comment by fbartho** [comment]
This is an old issue, I don't think this is a concern anymore. Please message back if we can't rely on ES6+ -- react-native core relies on ES6 these days.

**Comment by WaldoJeffers** [comment]
@fbartho This might be an "old" issue, but it's still valid, as you're only exporting an ES6 (with ES6 modules syntax), and not a browser-ready bundle. The problem is when you're trying to use your module outside of the Metro bundler context (it's not related to whether React Native uses ES6 internally or not), which _by default_ transpiles `node_modules` contrary to other bundlers such as Webpack or Rollup

**Comment by fbartho** [comment]
React Native Web made some different technical decisions than other libraries such as 
https://github.com/vincentriemer/react-native-dom or 
https://microsoft.github.io/reactxp 

It’s not clear to me that -web is the winning technical solution here. Adding a whole build tool chain for -web seems like a lot today. But if somebody contributes easy modifications to support it, then that might be okay (rollup). Are you sure you can’t configure your Babel or webpack to conditionally compile your node_modules?
