### ISSUE TITLE
Style prop does not works with parse

### ISSUE THREAD

**Issue by shukerullah** [taskrabbit/react-native-parsed-text#51]
`style` props is not working if I add `parse`.

```
<ParsedText
  parse={[
    { type: "url", style: styles.url, onPress: this.handleUrlPress }
  ]}
  style={styles.text}
>
  {children}
</ParsedText>
```

**Comment by fbartho** [comment]
@shukerullah -- if you still want this, somebody can add this as a feature.

The issue is that right now, we're merging the `<ParsedText`-style prop and it's conflicting with the style that's in the parameter.

One fix would be to apply *both* styles. Another fix would be to change the order that these props override each other.

Either of these would be breaking changes to the library, so we'd need to document it in README and add tests.

Please let me know if you're interested in submitting a PR to get started on this.

**Comment by magrinj** [comment]
@fbartho Why it's not working now, I used this library long time ago and that was working perfectly ?
I take a look in your code, and you directly pass the remaining props to Text, so I don't really understand why the style is not applied...

**Comment by magrinj** [comment]
@fbartho I create a PR for this
