### ISSUE TITLE
Some props style cant work 

### ISSUE THREAD

**Issue by catmans1** [taskrabbit/react-native-parsed-text#71]
i use the version
`
"react-native-parsed-text": "0.0.21",
`
It cant work with style
```
{
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    borderRadius: 10,
    marginRight: 5,
    fontSize: 12,
    textAlign: 'center',
    textAlignVertical: 'center',
    alignContent: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  }
```
Could anyone find solution for this?
Thank you!

**Comment by fbartho** [comment]
I'm not sure what the exact problem is @catmans1 -- did you figure this out?

Since this is a ticket from last year, I'm going to assume it's not valid anymore, but if you still have problems with what you're trying please write back and I'm happy to open it again.
If you find a bug or have a PR, I'm working on a new release in #79
