### ISSUE TITLE
Pattern for Bold and Italic is not working

### ISSUE THREAD

**Issue by MuhammadMattiullah** [taskrabbit/react-native-parsed-text#75]
```
Code:
{ pattern: /\*\*([a-zA-Z]+)\*\*/g, style: styles.bold },

Input:
This is the **bold** text
```
Required Output:
This is the **bold** text

Please can someone tell me @jrichardlai @fbartho

**Comment by BenScalabrin** [comment]
@MuhammadMattiullah 

add this in your json `renderText: (matchingString, matches) => matches[1]`

works to me

**Comment by socialcode-rob1** [comment]
Depending on your pattern, it could be a different element in the array

```
{
   pattern: /(\*\*|__)(.*?)\1/,
   style: styles.bold,
   renderText: (matchingString, matches) => matches[2],
},
```

**Comment by fbartho** [comment]
@MuhammadMattiullah both of the suggestions above would have been what I recommend for you.

I'm going to close this since there are ways to do what you ask, but if it doesn't work, please do comment back, and I'm happy to reopen it.

If you find a bug or have a PR, I'm working on a new release in #79
